[project]
name = "hw6"
version = "0.1.0"
description = "2025 spring ML"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "transformers",
    "peft",
    "datasets",
    "trl",
    "bitsandbytes",
    "tqdm",
    "ipython",
]

